"""Row-code generators — one helper per table.

Every row in NocoDB has a `code` column that uniquely identifies it (the
display field). Codes follow per-table naming conventions:

| Table                | Pattern                                     |
| -------------------- | ------------------------------------------- |
| `studies`            | manually set, e.g. `"ADVEI_2026"`           |
| `experiments`        | provided by the caller (e.g. lbp), e.g. `"ADVEI_2026_001"` |
| `dim_positions`      | `{domain}.d{depth}.{count}`                 |
| `set_study_constants`| `{study_code}/{constant_code}`              |
| `set_exp_params`     | `{exp_code}/{param_code}[/{dim_code}]`      |
| `set_exp_features`   | `{exp_code}/{feature_code}/{dim_code}`      |
| `set_exp_attributes` | `{exp_code}/{attribute_code}/{dim_code}`    |

Generated by the `pred-fab-nocodb` writer at insert time; consumers pass
only the meaningful parts and the writer assembles the full code.
"""
from __future__ import annotations


def make_dim_position_code(domain: str, depth: int, count: int) -> str:
    """Generate a `dim_positions.code`. Counter is per-(domain, depth)."""
    return f"{domain}.d{depth}.{count}"


def make_dataset_code(study_code: str, dataset_name: str) -> str:
    """Generate a `datasets.code`."""
    return f"{study_code}/{dataset_name}"


def make_study_constant_code(study_code: str, constant_code: str) -> str:
    """Generate a `set_study_constants.code`."""
    return f"{study_code}/{constant_code}"


def make_value_code(
    exp_code: str,
    value_code: str,
    dim_code: str | None = None,
) -> str:
    """Generate a `set_exp_*.code` (params, features, attributes share this pattern).

    `dim_code` is optional: omit for static params (no dim); include for
    trajectory params, features, and attributes.
    """
    if dim_code is None:
        return f"{exp_code}/{value_code}"
    return f"{exp_code}/{value_code}/{dim_code}"
